// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.geo.provider.use_gpsd", true);
user_pref("app.normandy.user_id", "fdc5ccea-7df1-4dce-86d5-88fb5ce90839");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1554308982);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1554309102);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1554305366);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1554308806);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1554308686);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1554309342);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1554309222);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 686080);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1554305336);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.impressionId", "{69275bde-e360-4477-b037-e172172a2d7d}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1554249600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1554305337);
user_pref("browser.onboarding.notification.prompt-count", 2);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1554308658340");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1554312258340");
user_pref("browser.search.countryCode", "ES");
user_pref("browser.search.region", "ES");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190207192912");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1554308952");
user_pref("browser.slowStartup.averageTime", 1136);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190207192912");
user_pref("browser.startup.homepage_override.mstone", "62.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1554305347331");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "62.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "033fb638b72847b1b9e56be1bd9a85ab");
user_pref("extensions.blocklist.lastModified", "Mon, 01 Apr 2019 11:50:27 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1554308982);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190207192912");
user_pref("extensions.lastAppVersion", "62.0.3");
user_pref("extensions.lastPlatformVersion", "62.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"e044fbc8-3ca9-4758-8972-147895cfe24b\",\"screenshots@mozilla.org\":\"cb8051e8-3618-44a9-91c4-f9d0be56a6c5\"}");
user_pref("idle.lastDailyNotification", 1554308836);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190207192912");
user_pref("media.gmp-manager.lastCheck", 1554305367);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1554308836);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e959fc5b-c6ff-4864-8e5b-7b4b99c5bf81");
user_pref("services.blocklist.addons.checked", 1554309130);
user_pref("services.blocklist.gfx.checked", 1554309130);
user_pref("services.blocklist.onecrl.checked", 1554309130);
user_pref("services.blocklist.pinning.checked", 1554309130);
user_pref("services.blocklist.plugins.checked", 1554309130);
user_pref("services.settings.clock_skew_seconds", -28);
user_pref("services.settings.last_etag", "\"1554301860877\"");
user_pref("services.settings.last_update_seconds", 1554309130);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1554308836);
user_pref("toolkit.startup.last_success", 1554308951);
user_pref("toolkit.telemetry.cachedClientID", "bb1364d8-7544-43a8-9889-bb1085ef18c6");
user_pref("toolkit.telemetry.previousBuildID", "20190207192912");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
